services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5500:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: unless-stopped
  
  # backend:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env
  #   restart: unless-stopped

volumes:
  postgres_data:
  pgadmin: